#!/bin/bash
# Start letta. Optionally create and configure a new project/agent.

set -e

source ~/.env

if [ -z "$LETTA_DEFAULT_MODEL" ]; then
	>&2 echo "Error: LETTA_DEFAULT_MODEL is not set"
	exit 1
fi

if [ "$HOME" = "$(pwd)" ]; then
	>&2 echo "Won't start in the home directory"
	exit 1
fi

if [ -d .letta ]; then
	/opt/homebrew/bin/letta "$@"
	exit 0
fi

read -p "Start a new Letta project? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
	/opt/homebrew/bin/letta --model "$LETTA_DEFAULT_MODEL" "$@"
	# todo? --sleeptime
	exit 0
fi

# todo
# 	python API client to create/configure agent
#       set name to `pwd`
# 		https://docs.letta.com/guides/templates/overview/
# 		context window = 99000
# 		how to link "human" block? https://app.letta.com/projects/default-project/blocks
# 			https://discord.com/channels/1161736243340640419/1452177709672304773

>&2 echo "no project created"
exit 1
